version: '3.8'

services:
  db:
    env_file: ./.env
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  api:
    env_file: ./.env
    build: ./backend
    container_name: ftchr_api_c
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: $MYSQLDB_USER
      DB_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      DB_NAME: $MYSQLDB_DATABASE

  app:
    build: ./frontend
    container_name: ftchr_app_c
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
volumes:
  db-data: