version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ftchr_db
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  api:
    build: ./backend
    container_name: ftchr_api_c
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: password

volumes:
  db-data: